### ISSUE TITLE
vis in node.js throwing errors?

### ISSUE THREAD

**Issue by gaggle** [almende/vis#1180]
Hi,

I wanted to try vis, and to that end I first wanted to use `DataSets` on the server (and worry about anything client-side for later, for now all I desire is to store and manipulate the data on the server).

But I can't `require("vis"`), it throws this:

    /usr/local/bin/node server.js
    .../node_modules/vis/lib/util.js:115
    exports.fillIfDefined = function (a, b, allowDeletion = false) {
                                                          ^
    SyntaxError: Unexpected token =
        at exports.runInThisContext (vm.js:73:16)
        at Module._compile (module.js:443:25)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (.../node_modules/vis/index.js:2:16)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)

    Process finished with exit code 1

Hm. I thought I'd be able to use this in node.js. I also tried `require("vis/lib/DataSet")` but that results in a slightly different error:

    /usr/local/bin/node server.js
    .../node_modules/vis/lib/DataSet.js:158
        this._subscribers[event] = subscribers.filter(listener => listener.callbac
                                                               ^^
    SyntaxError: Unexpected token =>
        at exports.runInThisContext (vm.js:73:16)
        at Module._compile (module.js:443:25)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (server.js:4:11)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)

    Process finished with exit code 1

Are we supposed to be able to use this in node.js? I think the `DataSet` class seems suitable as a container for my server, but maybe I'm going against your intentions..

This is using version `^4.7.0` and:

    $ npm version
    { npm: '2.13.4',
      http_parser: '2.3',
      modules: '14',
      node: '0.12.7',
      openssl: '1.0.1p',
      uv: '1.6.1',
      v8: '3.28.71.19',
      zlib: '1.2.8' }

**Comment by josdejong** [comment]
Thanks for bringing this up. vis.js uses ES6, and needs to be transpiled via [babel](https://babeljs.io/). You could do that on the fly using [`babel-node`](https://babeljs.io/docs/usage/cli/#babel-node) (for testing, not for production).

To load vis.js in node.js, you have to load the generated bundle: `require('vis/dist/vis.min.js')`.

The entry point for node.js was pointing to `./index.js`. I've changed that to the built `./lib/dist/vis.min.js` file, so you can load vis.js in node.js the regular way, using `require('vis')`
