### ISSUE TITLE
Fix build for latest stable version of module 'uglify-js'

### ISSUE THREAD

**Issue by wimrijnders** [almende/vis#3290]
This issue comes from an observation in PR #3287.

The latest stable version of `uglify-js` breaks the build. The build must be adjusted for the upgrade.

It concerns the following components:

- `uglify-js` current version `2.8.29`, latest stable `3.0.26`

**Comment by tibuurcio** [comment]
Hi!
When using webpack and trying to build for production with uglifyJs I'm getting the following error:

`Unexpected token operator «=», expected punc «,» [./node_modules/vis/lib/util.js:115,0]`

Is this related? Any suggestions how I can fix it?
Thanks!

**Comment by wimrijnders** [comment]
I don't think so. This is the warning if latest stable of `uglify-js` is installed:

```
npm WARN unmet dependency /home/wim/projects/github/vis/node_modules/webpack/node_modules/uglifyjs-webpack-plugin requires uglify-js@'^2.8.29' but will load
npm WARN unmet dependency /home/wim/projects/github/vis/node_modules/uglify-js,
npm WARN unmet dependency which is version 3.0.27
```


And this is the first of the errors during build:
```
TypeError: Cannot read property 'reset' of undefined
    at /home/wim/projects/github/vis/node_modules/webpack/node_modules/uglifyjs-webpack-plugin/dist/index.js:96:21
    at Array.forEach (native)
    at Compilation.<anonymous> (/home/wim/projects/github/vis/node_modules/webpack/node_modules/uglifyjs-webpack-plugin/dist/index.js:54:20)
    at next (/home/wim/projects/github/vis/node_modules/webpack/node_modules/tapable/lib/Tapable.js:186:14)
    at Compilation.<anonymous> (/home/wim/projects/github/vis/node_modules/webpack/lib/BannerPlugin.js:67:5)
    at Compilation.applyPluginsAsyncSeries (/home/wim/projects/github/vis/node_modules/webpack/node_modules/tapable/lib/Tapable.js:188:13)
    at /home/wim/projects/github/vis/node_modules/webpack/lib/Compilation.js:640:10
    at Compilation.applyPluginsAsyncSeries (/home/wim/projects/github/vis/node_modules/webpack/node_modules/tapable/lib/Tapable.js:177:46)
    at sealPart2 (/home/wim/projects/github/vis/node_modules/webpack/lib/Compilation.js:636:9)
    at Compilation.applyPluginsAsyncSeries (/home/wim/projects/github/vis/node_modules/webpack/node_modules/tapable/lib/Tapable.js:177:46)
```

You error looks more like an error on the `es2015` syntax. My thought would be that `babel` is not configured correctly. I'm not capable of giving you any advice of that due to lack of knowledge.
